title: 往見

author: Zhi Shao

description: Buddhism, Pali and Sanskrit Texts, Ancient Chinese Literature and History, etc.

url: http://ehipassa.org

permalink: /:title

timezone: Asia/Shanghai

markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap
