baseURL = "https://ehipassa.org/"
title = "往見"

hasCJKLanguage = true
languageCode = "zh"

disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
contentUrl = "https://content.ehipassa.org/"
description = "Theravada Buddhism 佛教 上座部 古籍"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
